title: Dongyi (Philip) Xue # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a machine learning / software development engineer working at Tokyo, Japan. My current expertise are in the 
  field of computer vision
  <br><br>
  I like 
  <br><br>
  <a href="https://www.linkedin.com/in/philipxue/">View my LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.kaggle.com/philipxue/">View my Kaggle Profile</a>
  <br><br>
  <a href="/pdf/Philip_resume.pdf?raw=true">View my English CV</a>
  <br><br>
  <a href="/pdf/Philip_resume_JP.pdf?raw=true">日本語履歴書はこちら</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
