title: Dongyi (Philip) Xue # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a machine learning / software development engineer working at Tokyo, Japan. My main expertise are in the 
  field of computer vision but I'm also have knowledge other field in machine learning like NLP and recommender
   system. I also focus on the engineering chanllenges to put machine learning model into production.
  <br><br>
  Besides works, I love custom PC building. I also enjoy putting in effort in
  improving the ergonomics at my workspace and living space.
  I am a sports fun, and played amauteur basketball at college.
  <br><br>
  I also speaks 3 lanuages, English, Mandarin, and Japanese, all at full profession proficiency. Linguistics
  is another field of intertest for me and I plan to pick up some other lanuages or dialect in the future.
  <br><br>
  <a href="https://www.linkedin.com/in/philipxue/">View my LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.kaggle.com/philipxue/">View my Kaggle Profile</a>
  <br><br>
  <a href="/pdf/Philip_resume.pdf?raw=true">View my English CV</a>
  <br><br>
  <a href="/pdf/Philip_resume_JP.pdf?raw=true">日本語履歴書はこちら</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
